- README.md
Added a basic readme to root for first comers.
> chore: add a basic readme to root

- apps/discord-bot/.env.example
- apps/discord-bot/.gitignore
- apps/discord-bot/README.md
- apps/discord-bot/main.py
- apps/discord-bot/requirements.txt
Hi, please take a look at this and see if everything is ok to be merged thank you! :)
> chore(env): setup development and production python venvs

- .dockerignore
- apps/web/Dockerfile.dev
- apps/web/package.json
- apps/web/src/routes/index.tsx
- docker-compose.dev.yaml
Added a Dockerfile.dev for `web/` for development.
> build: development dockerfile for web

- apps/api/Makefile
- apps/api/internal/db/migrations/20250619161938_event_schema.sql
- apps/api/internal/db/sqlc/models.go
Adds the event schema to the db, here is the shape of this in the `public` schema.
> feat: event schema

- apps/web/package.json
Renamed openapi file from `swagger.yaml` to `core-api.yaml` for more accurate naming and consistent style.
None.
- Refactor
N/A
> ref: change openapi yaml from swagger.yaml to core-api.yaml

- .github/workflows/api/build-and-push.yml
- apps/api/.dockerignore
- apps/api/Dockerfile
Builds a production ready API and pushes the image to ghcr!
----
- New feature (non-breaking change)
> Dockerfile and workflow for API image build and push to GHCR

- infra/docker-compose.dev.yml
- infra/docker-compose.yml
> feat: swamphacks infra files

- apps/web/src/routes/_main/community.tsx
- apps/web/src/routes/_main/layout.tsx
- apps/web/src/routes/_main/portal.tsx
- apps/web/src/routes/_main/resources/programming.tsx
- apps/web/src/routes/_main/resources/sponsors.tsx
- apps/web/src/routes/admin/layout.tsx
Links to admin dashboard
- New feature (non-breaking change)
> Admin dashboard links

- apps/web/src/routes/_main/community.tsx
- apps/web/src/routes/_main/layout.tsx
- apps/web/src/routes/_main/portal.tsx
- apps/web/src/routes/_main/resources/programming.tsx
- apps/web/src/routes/_main/resources/sponsors.tsx
- apps/web/src/routes/admin/layout.tsx
> Some dashboard links and more

- apps/api/cmd/api/main.go
- apps/api/cmd/email_worker/main.go
> fix redis url

- apps/api/go.sum
- apps/api/internal/api/api.go
- apps/api/internal/api/handlers/events.go
- apps/api/internal/ctxutils/user.go
- apps/api/internal/db/queries/events.sql
- apps/api/internal/db/repository/events.go
- apps/api/internal/db/sqlc/events.sql.go
- apps/api/internal/db/sqlc/querier.go
- apps/api/internal/ptr/bool.go
- apps/api/internal/services/events.go
- apps/api/internal/web/query.go
- apps/api/sqlc.yml
- apps/web/package.json
- apps/web/pnpm-lock.yaml
- apps/web/src/features/Admin/EventManager/hooks/useAdminEvents.ts
- apps/web/src/features/Event/components/EventButton.tsx
- apps/web/src/features/Event/components/EventCard.tsx
- apps/web/src/features/Event/hooks/useEventsWithUserInfo.ts
- apps/web/src/features/Event/utils/mapper.ts
- apps/web/src/lib/openapi/schema.d.ts
- apps/web/src/lib/openapi/types.ts
- apps/web/src/routes/_main/portal.tsx
- apps/web/src/routes/events/$eventId/dashboard/index.tsx
- apps/web/src/routes/events/$eventId/feedback/declined.tsx
- apps/web/src/routes/events/$eventId/rejected.tsx
- apps/web/src/routes/events/$eventId/summary.tsx
- apps/web/src/routes/events/$eventId/waitlist/info.tsx
- shared/openapi/core-api.yaml
Adding real functionality to event cards
- New feature (non-breaking change)
> Event cards API Integration

- apps/api/internal/api/handlers/event_interest.go
> Fix: updated error message

- apps/api/internal/api/api.go
> Release 3.0.1 (hotfix)

- apps/api/go.mod
- apps/api/go.sum
- apps/api/internal/api/api.go
> ADHOC: interest rate limiter

- apps/api/cmd/api/main.go
- apps/api/internal/api/api.go
- apps/api/internal/api/handlers/handlers.go
- apps/api/internal/api/handlers/user.go
- apps/api/internal/db/migrations/20250905210705_add_preferred_email_column.sql
- apps/api/internal/db/queries/users.sql
- apps/api/internal/db/repository/users.go
- apps/api/internal/db/sqlc/event_roles.sql.go
- apps/api/internal/db/sqlc/models.go
- apps/api/internal/db/sqlc/users.sql.go
- apps/api/internal/services/user.go
- apps/web/src/features/Onboarding/components/OnboardingModal.tsx
- apps/web/src/routes/_main/portal.tsx
New Handler and Service for User usecases
users/me GET endpoint for getting user information
users/me POST endpoint for updating user information (right now only name and email)
users/me/onboarded POST endpoint for updating onboarded (only for onboarded)
The two POST can be combined into one general endpoint perhaps
If the user isn't onboarded and a skipped onboarding cookie isn't present, the modal appears
Modal asks for name (one field) and email (with light validation)
Skipping sets a cookie: welcome-modal-skipped = true
> Added Introduction Modal

- apps/web/src/features/Dashboard/components/ApplicantAppShell.tsx
- apps/web/src/features/Event/utils/mapper.ts
Very quick PR that refactors the switch statement in Event/utils/mapper.ts into a map. 
Renamed the Team Formation to My Team in applicant dashboard.
- Bug fix (non-breaking change)
- Refactor
> Event Status Mapping Refactor + Team Management Tab Renaming

- apps/web/src/components/ui/Card/Card.stories.tsx
- apps/web/src/components/ui/FileField/FileField.stories.tsx
- apps/web/src/components/ui/Select/Select.stories.tsx
- apps/web/src/features/Event/api/getUserEventRole.ts
- apps/web/src/features/Event/components/stories/EventButton.stories.tsx
- apps/web/src/features/Event/components/stories/EventCard.stories.tsx
- apps/web/src/features/FormBuilder/stories/example.stories.tsx
- apps/web/src/features/PlatformAdmin/EventManager/hooks/useCreateAdminEvent.ts
- apps/web/src/routes/_protected/events/$eventId/dashboard/layout.tsx
- apps/web/vite.config.ts
Fixed typescript type errors for production web build.
[TECH-220](https://swamphacks.atlassian.net/browse/TECH-220)
- Bug fix (non-breaking change)
> Fix typescript errors for production build

- apps/web/Dockerfile
- apps/web/entrypoint.sh
- apps/web/index.html
- apps/web/public/env-config.js
- apps/web/src/config/env.ts
> fix(build): now injects runtime variables

- .github/workflows/dev-build-deploy-api.yml
- .github/workflows/dev-build-deploy-email-worker.yml
- .github/workflows/prod-build-deploy-api.yml
- .github/workflows/prod-build-deploy-email-worker.yml
- infra/Caddyfile.api
- infra/docker-compose.api.yml
> feat(CI/CD): build and deploy new api to digital ocean

- .github/workflows/dev-build-deploy-api.yml
- .github/workflows/dev-build-deploy-email-worker.yml
- .github/workflows/prod-build-deploy-api.yml
- .github/workflows/prod-build-deploy-email-worker.yml
- apps/web/Dockerfile
- apps/web/entrypoint.sh
- apps/web/index.html
- apps/web/public/env-config.js
- apps/web/src/config/env.ts
- infra/Caddyfile.api
- infra/docker-compose.api.yml
> Build and deploy API
